name: API Test with Bruno

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
      pr-id:
        required: false
        type: string

jobs:
  test-api:
    timeout-minutes: 10
    name: API Test in ${{ inputs.environment }} environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Bru CLI from NPM
        run: npm install -g @usebruno/cli
      - name: Run tests
        run: bru run --env ${{ inputs.environment }} --output report.xml --format junit
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report
          path: report.xml
          reporter: java-junit

  feedback-on-pr:
    timeout-minutes: 10
    name: Feedback on Pull Request
    needs: test-api
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        if: ${{ inputs.pr-id }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hi Team, ${{ inputs.environment }} env API test completed! :rocket:
          reactions: eyes
          pr_number: ${{ inputs.pr-id }}
      - name: Add Label
        if: ${{ inputs.pr-id }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          number: ${{ inputs.pr-id }}
          labels: api
