name: Cloudflare Pages Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      output:
        required: true
        type: string
      hostname:
        required: false
        type: string
      ga-measurement:
        required: false
        type: string
      sentry-project-id:
        required: false
        type: string
      sentry-org-id:
        required: false
        type: string
      pr-id:
        required: false
        type: string
    outputs:
      result:
        description: "Deployment results"
        value: ${{ jobs.deploy.outputs.result }}

jobs:

  deploy:
    timeout-minutes: 10
    name: Deploy to ${{ inputs.environment }} environment
    # needs: build
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.result }}
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.hostname }}
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build application
        run: |
          npm ci
          npm run build --if-present
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          GA_MEASUREMENT: ${{ inputs.ga-measurement }}
          SENTRY_PUBLIC_KEY: ${{ secrets.SENTRY_PUBLIC_KEY }}
          SENTRY_PROJECT_ID: ${{ inputs.sentry-project-id }}
          SENTRY_ORG_ID: ${{ inputs.sentry-org-id }}
          PUBLIC_API_HOSTNAME: ${{ vars.PUBLIC_API_HOSTNAME }}
          PUBLIC_TURNSLITE_KEY_INVISIBLE: ${{ secrets.PUBLIC_TURNSLITE_KEY_INVISIBLE }}
          PUBLIC_TURNSLITE_KEY_MANAGED: ${{ secrets.PUBLIC_TURNSLITE_KEY_MANAGED }}
          PUBLIC_GOOGLE_MAP_KEY: ${{ secrets.PUBLIC_GOOGLE_MAP_KEY }}
      - name: Publish to Cloudflare Pages
        id: publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT }}
          directory: ${{ inputs.output }}
          branch: main
          # workingDirectory: app
          wranglerVersion: "3"
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"
      - name: Set deployment result
        id: result
        run: echo "result=${{ job.status }}" >> $GITHUB_OUTPUT

  feedback-on-pr:
    timeout-minutes: 10
    name: Feedback on Pull Request
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        if: ${{ inputs.pr-id }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hi @Aliaic, ${{ inputs.environment }} env deployment successful! :rocket:
            Preview URL is ready: https://${{ inputs.hostname }}
          reactions: eyes, rocket
          pr_number: ${{ inputs.pr-id }}
          comment_tag: deployment
      - name: Add Label
        if: ${{ inputs.pr-id }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          number: ${{ inputs.pr-id }}
          labels: ${{ inputs.environment }}
