name: Vercel Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      env-url:
        required: false
        type: string
      pr-id:
        required: false
        type: string
    outputs:
      url:
        description: "Deployment URL"
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  deploy:
    timeout-minutes: 10
    name: Deploy to ${{ inputs.environment }} environment
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.publish.outputs.url }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.env-url }}
    permissions:
      contents: read
      deployments: write
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ENV: ${{ (inputs.environment == 'test' || inputs.environment == 'production') && 'production' || 'preview' }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_BUILD_CMD: ${{ (inputs.environment == 'test' || inputs.environment == 'production') && 'vercel build --prod --token=' || 'vercel build --token=' }}
      VERCEL_DEPLOY_CMD: ${{ (inputs.environment == 'test' || inputs.environment == 'production') && 'vercel deploy --prebuilt --prod --token=' || 'vercel deploy --prebuilt --token=' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN
      - name: Build Project Artifacts
        run: $VERCEL_BUILD_CMD$VERCEL_TOKEN
      - name: Deploy Project Artifacts to Vercel
        id: publish
        run: |
          DEPLOY_OUTPUT=$($VERCEL_DEPLOY_CMD$VERCEL_TOKEN)
          echo "url=$DEPLOY_OUTPUT" >> $GITHUB_OUTPUT
      - name: Set deployment result
        id: result
        run: echo "result=${{ job.status }}" >> $GITHUB_OUTPUT

  feedback-on-pr:
    timeout-minutes: 10
    name: Feedback on Pull Request
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        if: ${{ inputs.pr-id }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hi Team, ${{ inputs.environment }} env deployment successful! :rocket:
            Vercel Preview URL is ready: ${{ needs.deploy.outputs.url }}
            Environment Preview URL is ready: ${{ inputs.env-url }}
          reactions: eyes, rocket
          pr_number: ${{ inputs.pr-id }}
      - name: Add Label
        if: ${{ inputs.pr-id }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          number: ${{ inputs.pr-id }}
          labels: ${{ inputs.environment }}
